[context.staging.environment]
  API_URL = "https://staging.api.synthetix.io/api/"

[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  API_URL = "https://api.synthetix.io/api/"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "10.16.3"
  RUBY_VERSION = "2.6.2"
